spring:
  datasource:
    url: jdbc:h2:mem:testdb;Mode=MySQL

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect
    open-in-view: false

  h2:
    console:
      enabled: true

  thymeleaf:
    cache: false
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html

  profiles:
    active: local
---
spring:
  config:
    activate:
      on-profile: local
    import: sub/local/application-db.yml
---
spring:
  config:
    activate:
      on-profile: dev
    import: sub/dev/application-db.yml