spring:
  datasource:
    url: jdbc:h2:mem:testdb;Mode=MySQL

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect
    open-in-view: false

  h2:
    console:
      enabled: true

  thymeleaf:
    cache: false
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html

  messages:
    basename: message.errors

  config:
    import: secure/application-aws.yml, secure/application-enc.yml

  profiles:
    active: local

logging:
  level:
    org:
      apache:
        coyote:
          http11: info

---
spring:
  config:
    activate:
      on-profile: local
    import: secure/local/application-db.yml
---
spring:
  config:
    activate:
      on-profile: dev
    import: secure/dev/application-db.yml